spring:
  application:
    name: approval-flow-api

  datasource:
    url: jdbc:h2:mem:approvalflow
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  spring:
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info